language: android

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository

script:
  - ./gradlew test

jdk:
  - oraclejdk8

before_install:
  - chmod +x .buildscript/deploy_snapshot.sh

after_success:
  - .buildscript/deploy_snapshot.sh

cache:
  directories:
    - $HOME/.gradle

sudo: false

env:
  global:
    - secure: yzljaHfWdmkAd782pY+Fp1jB/PR7vYArhDfvy19eP4yzkn+lorb/QcC2UM2XTMeHQOvYxUXYUPSXlmq0ZgnXso6WNynBr7Y4vdkoDr5whQGOLV0yA1vg+n4mn75i9pCVugiK1PJsy4CDjRUtli+cvDoRZ9dBCsuxbaOrv+xFCn3aM14zsgNEAmIX4oltyRBTO74N9jDK1xKxoUD6U8HKfIWOgPC2cgxJNBCT1c4nGgnV7CXHOfh6GpLFNYsq2Hl/6obrg8YdXDQwROhD/sKaiAypvgQJXOnKl6AuqFgrimFjKK/bJDhkPd7X+i6LH9SWjokL9yn2eMmMuuwWw+3yZ5z/bYe+5R33PBaN/n+32h2qAzsOpmMWRwTLLQ3Q/mZmnSXOvLT0zPm/mx5nYOk7ouKWgfPmxXNXRsWLQV7vsdWkxFby65EKumVBi1CO/le8Yt6BOPoot0iZwnUQLLBYHLx5VIcDkR1H0iKoihf3sLDlCkQihEZ+pKSavbQ22sziQl3JhOt+m92vSWR8XICF0ChYE3vVLxlGM8vxALE8nShIqry0AKihIMLiWAl9Xqn56CNBYsVXamHS4C2mOmh7nHb1wRgxxJsKn7jX2ToBKio+hRHsE+f0MROuQwCz0tYl7vk8IqjfMfAgvv2JKaPDBVYP4gBs4OmmKvmAxut+iOc=
    - secure: GMTh7UbPwnQVZJzHVm3kyRXi5aVSGSWiZACAVlJvY+/aG87JgjB9tpy/9C51mrEHbP3YdQ66DQLOzlEtcp99mNVnT2Lp9nHh5T+IxsIHwUpBjyhg9YtmKMoAlyfZKFqVP/3noGSbcSra9BBiKnB/of/HF63fJ3LYc2wVeQInU2H/eZxXISb2PfM1LIwdYNrC1q99Cn090gK1AATcVe1KvL74TefA3Uua/r/UMGLKUDMx+TlEwYQda7ylCCpOB6qky0f5dSTbXrsAG9mDMqKJ0wzmT5NZk9ewMzQZ7nQtXJVxnu+IH75IHu/gSI92x/GE5Z+X3AjFeiAoSF9DdaMIZxR6sZzIjhiP27Os8oXhPdn56RhlL7jXlOxMWe/NUjQLFeD52Rg/RMDDbmEAvNsDj6eT1+OBVU/v7dFxiIOS4aUE3+8rGddsfcEbDcdlBALnfygRWv6bW057iGEVGuYYfH54t/cQcN9laSjWcpVwCExxD5IdgYcfuvU3CPAHI20kNt6necmFnX8dKBXnd1SXmtout2gLJ46joP3tbhaI1eMsY9+7XkZ5mwGQfYnm2nwbH6q5tY2IhDZ9tI+F/VExRlLROd68GGU9Kfiee9ET1o5J4R+Fn95dwpoIQBeq/5PyiWlWO33kHHv3Hoxe6BN5qiAz5RElyMvO423T4EjIJ9c=
